### ISSUE TITLE
BUG - Table names in src_klaviyo.yml aren't configurable

### ISSUE THREAD

**Issue by tokybe** [fivetran/dbt_klaviyo_source#5]
**Are you a current Fivetran customer?** 
Hi, Toky here, I'm a data engineer at Dija.

**Describe the bug**
Since the table names in src_klaviyo.yml are hard-coded and not using the following variables
```yml
vars:
  klaviyo_source:
    event_table: "{{ source('klaviyo', 'event') }}" 
    campaign: "{{ source('klaviyo', 'campaign') }}" 
    flow: "{{ source('klaviyo', 'flow') }}" 
    integration: "{{ source('klaviyo', 'integration') }}" 
    person: "{{ source('klaviyo', 'person') }}" 
    metric: "{{ source('klaviyo', 'metric') }}"
```
`dbt source snapshot-freshness` will always look for the default table names.

**Steps to reproduce**
1. Set different target names for the klaviyo_source tables
2. Run `dbt source snapshot-freshness`
3. It fails with 
```
Runtime Error in source campaign (models/src_klaviyo.yml)
  404 Not found: Table <project_id>:<klaviyo_source_schema>.campaign was not found in location <location>
```

**Expected behavior**
`dbt source snapshot-freshness` finds klaviyo source tables when they don't have their default names.

**Project variables configuration**

```yml
models:
 klaviyo_source:
     +schema:  # leave blank for just the target_schema

vars:
  klaviyo_source:
    event_table: "{{ ref('stg_klaviyo__event_base') }}" 
    campaign: "{{ ref('stg_klaviyo__campaign_base') }}" 
    flow: "{{ ref('stg_klaviyo__flow_base') }}" 
    integration: "{{ ref('stg_klaviyo__integration_base') }}" 
    person: "{{ ref('stg_klaviyo__person_base') }}" 
    metric: "{{ ref('stg_klaviyo__metric_base') }}"
  klaviyo_schema:
```

**Package Version**
```yml
packages:
  - package: fivetran/klaviyo_source 
    version: [">=0.1.0","<0.2.0"]
```

**Warehouse**

 
- [X] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 
This doens't allow us to have freshness information for our klaviyo source tables.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [X] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
